In [1]:
import torch
import numpy as np

In [2]:
data= [[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [5]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [6]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [7]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [8]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [9]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [10]:
a[1,1]

tensor(1.)

In [12]:
a[1,1].item()

1.0

In [16]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])

In [14]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [15]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [17]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.6477, 0.6040],
        [0.5447, 0.3172]])

In [18]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.5235, 0.9856, 0.8366],
        [0.7228, 0.0231, 0.4899]])

In [19]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
rand_tensor.shape

torch.Size([2, 3])

In [22]:
rand_tensor.dtype

torch.float32

In [23]:
rand_tensor.device

device(type='cpu')

In [24]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [52]:
rand_tensor.device

device(type='cpu')

In [25]:
 rand_tensor

tensor([[0.5235, 0.9856, 0.8366],
        [0.7228, 0.0231, 0.4899]])

In [26]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.5235, 1.0000, 0.8366],
        [0.7228, 1.0000, 0.4899]])

In [27]:
rand_tensor[0]

tensor([0.5235, 1.0000, 0.8366])

In [28]:
rand_tensor[:,0]

tensor([0.5235, 0.7228])

In [29]:
rand_tensor[...,-1]

tensor([0.8366, 0.4899])

In [30]:
rand_tensor.sum()

tensor(4.5728)

In [31]:
rand_tensor.sum().item()

4.57279634475708

In [32]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.5235, 1.0000, 0.8366, 0.0000, 0.0000, 0.0000],
        [0.7228, 1.0000, 0.4899, 0.0000, 0.0000, 0.0000]])

In [33]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.5235, 1.0000, 0.8366],
        [0.7228, 1.0000, 0.4899],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [34]:
rand_tensor.mul(ones_tensor)

tensor([[0.5235, 1.0000, 0.8366],
        [0.7228, 1.0000, 0.4899]])

In [35]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.9740, 1.7882],
        [1.7882, 1.7624]])

In [36]:
rand_tensor.add_(5)

tensor([[5.5235, 6.0000, 5.8366],
        [5.7228, 6.0000, 5.4899]])

In [37]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [38]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [39]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [40]:
x = torch.empty(1)
print(x)

tensor([3.7788e+37])


In [41]:
x.size()

torch.Size([1])

In [42]:
x = torch.empty(2,3)
print(x)

tensor([[7.5452e-13, 3.0971e-41, 6.4039e-13],
        [3.0971e-41, 3.0881e+29, 1.5766e-19]])


In [43]:
torch.empty(2,2,3)

tensor([[[3.7788e+37, 4.3552e-41, 6.9744e-13],
         [3.0971e-41, 4.4842e-44, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00, 7.0000e+08],
         [3.0967e-41, 2.0000e+00, 2.3431e+00]]])

In [51]:
y=x.view(6)
y

tensor([7.5452e-13, 3.0971e-41, 6.4039e-13, 3.0971e-41, 3.0881e+29, 1.5766e-19])

In [45]:
z=x.view(1,-1)
z

tensor([[7.5452e-13, 3.0971e-41, 6.4039e-13, 3.0971e-41, 3.0881e+29, 1.5766e-19]])