In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array(42)
print(arr)


42


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])

2


In [ ]:
print(arr[2] + arr[3])

7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[4:])

[5 6 7]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[-3:-1])

[5 6]


In [ ]:

print(arr[1:5:2])

[2 4]


In [ ]:
print(arr[::2])

[1 3 5 7]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
print(arr[0:2, 2])

[3 8]


In [ ]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
temparr = arr.reshape(4, 3)
print(temparr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
temparr = arr.reshape(2, 3, 2)
print(temparr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
newarr = arr.reshape(3, 3)# there is have error
print(newarr)

ValueError: ignored

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
temp = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)#1 means colum
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2)) #h means stack along rows
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2, 3],[3, 5, 6]])
arr2 = np.array([[4, 5, 6],[3, 5, 6]])
arr = np.vstack((arr1, arr2)) #v means stack along collum
print(arr)

[[1 2 3]
 [3 5 6]
 [4 5 6]
 [3 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


In [ ]:
x = np.searchsorted(arr, 7)
print(x)

6


In [ ]:
x = np.searchsorted(arr, 7, side='right')
print(x)

7


In [ ]:
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 3 5]


In [ ]:
arr = np.array([3,4,9,2,5,7,65,4])
print(np.sort(arr))

[ 2  3  4  4  5  7  9 65]


In [ ]:
arr1 = np.array([[3, 2, 8],[3, 9, 6]])
arr2 = np.array([[4, 6, 5],[2, 5, 1]])
arr = np.vstack((arr1, arr2)) #v means stack along collum
print(arr)
print(np.sort(arr))

[[3 2 8]
 [3 9 6]
 [4 6 5]
 [2 5 1]]
[[2 3 8]
 [3 6 9]
 [4 5 6]
 [1 2 5]]


In [ ]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
